services:
  server:
    build:
      context: ./server
    env_file:
      - path: ./.env.local
        required: false
      - path: ./app/.env.local
        required: false
    ports:
      - "5173:5173"
    volumes:
      - ./server:/app
      - server-node-modules:/app/node_modules

  app:
    build:
      context: ./app
    env_file:
      - path: ./.env.local
        required: false
      - path: ./app/.env.local
        required: false
    ports:
      - "8080:5173"
    volumes:
      - ./app:/app
      - app-node-modules:/app/node_modules
    depends_on:
      - server

volumes:
  server-node-modules:
  app-node-modules:
